# The PROJECT variable must match the
# toplevel VHDL entity name (here: entity ledcomb)
# and should match the directory name in the pnr directory

PROJECT = ledcomb

# Define the list of VHDL files for this project
SOURCE_FILES = ../../src/ledcomb_rtl.vhd

include ../makefile
