# The PROJECT variable must match the
# toplevel VHDL entity name
# and should match the directory name in the pnr directory

PROJECT = de1_ledcntsw

SOURCE_FILES = \
../../src/de1_ledcntsw_rtl.vhd \
../../src/cntones_rtl.vhd

include ../makefile
