# The PROJECT variable must match the
# toplevel VHDL entity name
# and should match the directory name in the pnr directory

PROJECT = de1_bin2seg

SOURCE_FILES = \
../../src/de1_bin2seg_rtl.vhd \
../../src/bin2seg_rtl.vhd

include ../makefile
